package com.example.core.localization

data class FeatureStrings(
    val collectionCenter: String,
    val collectionSubtitle: String,
    val overdue: String,
    val dueToday: String,
    val dueSoon: String,
    val upcoming: String,
    val dueDate: String,
    val noDueDate: String,
    val setDueDate: String,
    val clearDueDate: String,
    val overdueDays: (Int) -> String,
    val dueInDays: (Int) -> String,
    val noCollections: String,
    val remindWhatsApp: String,
    val recordPayment: String,
    val settleFullCustomer: String,
    val settleFullSupplier: String,
    val fullSettlementNote: String,
    val attachDocument: String,
    val replaceAttachment: String,
    val removeAttachment: String,
    val attachmentAdded: String,
    val openAttachment: String,
    val biometricLock: String,
    val biometricLockDesc: String,
    val biometricUnavailable: String,
    val unlock: String,
    val unlockTitle: String,
    val unlockSubtitle: String,
    val calendarTitle: String,
    val gregorianCalendar: String,
    val ethiopianCalendar: String,
    val reminderMessage: (String, String, String) -> String
)

object FeatureStringsProvider {
    fun get(language: AppLanguage): FeatureStrings = when (language) {
        AppLanguage.ARABIC -> FeatureStrings(
            collectionCenter = "مركز التحصيل",
            collectionSubtitle = "تابع الديون المستحقة والمتأخرة في مكان واحد",
            overdue = "متأخر",
            dueToday = "مستحق اليوم",
            dueSoon = "مستحق قريبًا",
            upcoming = "قادم",
            dueDate = "موعد السداد",
            noDueDate = "بدون موعد سداد",
            setDueDate = "تحديد موعد السداد",
            clearDueDate = "إزالة الموعد",
            overdueDays = { "متأخر $it يوم" },
            dueInDays = { "متبقي $it يوم" },
            noCollections = "لا توجد ديون مستحقة للمتابعة حاليًا",
            remindWhatsApp = "تذكير واتساب",
            recordPayment = "تسجيل دفعة",
            settleFullCustomer = "استلام كامل الرصيد",
            settleFullSupplier = "دفع كامل الرصيد",
            fullSettlementNote = "تسديد كامل الرصيد",
            attachDocument = "إرفاق صورة أو PDF",
            replaceAttachment = "استبدال المرفق",
            removeAttachment = "حذف المرفق",
            attachmentAdded = "تم إرفاق مستند",
            openAttachment = "فتح المرفق",
            biometricLock = "قفل التطبيق بالبصمة",
            biometricLockDesc = "اطلب البصمة عند فتح DeynBook",
            biometricUnavailable = "البصمة غير متاحة أو غير مفعلة على هذا الجهاز",
            unlock = "فتح التطبيق",
            unlockTitle = "DeynBook مقفل",
            unlockSubtitle = "استخدم بصمتك للوصول إلى بيانات الديون",
            calendarTitle = "نظام التاريخ",
            gregorianCalendar = "التقويم الميلادي",
            ethiopianCalendar = "التقويم الإثيوبي",
            reminderMessage = { name, amount, due -> "مرحبًا $name، هذا تذكير ودي بأن الرصيد المستحق هو $amount، وموعد السداد $due. شكرًا لك." }
        )
        AppLanguage.SOMALI -> FeatureStrings(
            collectionCenter = "Xarunta Ururinta",
            collectionSubtitle = "Hal meel kaga raac deymaha waqtigoodu dhacay ama soo dhow",
            overdue = "Waqtigu dhaafay",
            dueToday = "Maanta ku eg",
            dueSoon = "Dhawaan ku eg",
            upcoming = "Soo socda",
            dueDate = "Taariikhda bixinta",
            noDueDate = "Taariikh bixineed ma leh",
            setDueDate = "Deji taariikhda bixinta",
            clearDueDate = "Ka saar taariikhda",
            overdueDays = { "$it maalmood ayuu dhaafay" },
            dueInDays = { "$it maalmood ayaa haray" },
            noCollections = "Ma jiraan deymo u baahan dabagal hadda",
            remindWhatsApp = "Xusuusi WhatsApp",
            recordPayment = "Diiwaan geli lacag-bixin",
            settleFullCustomer = "Qaado dhammaan hadhaaga",
            settleFullSupplier = "Bixi dhammaan hadhaaga",
            fullSettlementNote = "Bixinta hadhaaga oo dhan",
            attachDocument = "Ku lifaaq sawir ama PDF",
            replaceAttachment = "Beddel lifaaqa",
            removeAttachment = "Ka saar lifaaqa",
            attachmentAdded = "Dukumenti waa ku lifaaqan yahay",
            openAttachment = "Fur lifaaqa",
            biometricLock = "Ku xiro faraha",
            biometricLockDesc = "Dalbo faraha marka DeynBook la furayo",
            biometricUnavailable = "Aqoonsiga faraha lama heli karo ama lama dejin qalabkan",
            unlock = "Fur app-ka",
            unlockTitle = "DeynBook waa xiran yahay",
            unlockSubtitle = "Isticmaal farahaaga si aad u gasho xogta deymaha",
            calendarTitle = "Habka taariikhda",
            gregorianCalendar = "Kalandarka Gregorian",
            ethiopianCalendar = "Kalandarka Itoobiya",
            reminderMessage = { name, amount, due -> "Salaan $name, tani waa xusuusin saaxiibtinimo: hadhaaga lagugu leeyahay waa $amount, taariikhda bixintuna waa $due. Mahadsanid." }
        )
        AppLanguage.AMHARIC -> FeatureStrings(
            collectionCenter = "የክፍያ መከታተያ",
            collectionSubtitle = "የደረሱና ያለፉ ዕዳዎችን በአንድ ቦታ ይከታተሉ",
            overdue = "ጊዜው ያለፈ",
            dueToday = "ዛሬ የሚከፈል",
            dueSoon = "በቅርቡ የሚከፈል",
            upcoming = "ቀጣይ",
            dueDate = "የክፍያ ቀን",
            noDueDate = "የክፍያ ቀን የለም",
            setDueDate = "የክፍያ ቀን ይምረጡ",
            clearDueDate = "ቀኑን አስወግድ",
            overdueDays = { "$it ቀን ዘግይቷል" },
            dueInDays = { "$it ቀን ቀርቷል" },
            noCollections = "አሁን ክትትል የሚፈልግ ዕዳ የለም",
            remindWhatsApp = "በWhatsApp አስታውስ",
            recordPayment = "ክፍያ መዝግብ",
            settleFullCustomer = "ሙሉ ቀሪ ሂሳብ ተቀበል",
            settleFullSupplier = "ሙሉ ቀሪ ሂሳብ ክፈል",
            fullSettlementNote = "ሙሉ ቀሪ ሂሳብ ክፍያ",
            attachDocument = "ምስል ወይም PDF አያይዝ",
            replaceAttachment = "አባሪውን ቀይር",
            removeAttachment = "አባሪውን አስወግድ",
            attachmentAdded = "ሰነድ ተያይዟል",
            openAttachment = "አባሪውን ክፈት",
            biometricLock = "በጣት አሻራ ቆልፍ",
            biometricLockDesc = "DeynBook ሲከፈት የጣት አሻራ ይጠይቅ",
            biometricUnavailable = "የጣት አሻራ በዚህ መሣሪያ ላይ አይገኝም ወይም አልተዘጋጀም",
            unlock = "መተግበሪያውን ክፈት",
            unlockTitle = "DeynBook ተቆልፏል",
            unlockSubtitle = "የዕዳ መረጃዎን ለማየት የጣት አሻራዎን ይጠቀሙ",
            calendarTitle = "የቀን ስርዓት",
            gregorianCalendar = "ግሪጎሪያን የቀን መቁጠሪያ",
            ethiopianCalendar = "የኢትዮጵያ የቀን መቁጠሪያ",
            reminderMessage = { name, amount, due -> "ሰላም $name፣ ይህ ወዳጃዊ ማስታወሻ ነው። የሚከፈለው ቀሪ ሂሳብ $amount ሲሆን የክፍያ ቀኑ $due ነው። እናመሰግናለን።" }
        )
        AppLanguage.FRENCH -> FeatureStrings(
            collectionCenter = "Centre de recouvrement",
            collectionSubtitle = "Suivez les dettes échues et à venir au même endroit",
            overdue = "En retard",
            dueToday = "Échéance aujourd’hui",
            dueSoon = "Échéance proche",
            upcoming = "À venir",
            dueDate = "Date d’échéance",
            noDueDate = "Sans date d’échéance",
            setDueDate = "Définir l’échéance",
            clearDueDate = "Supprimer l’échéance",
            overdueDays = { "$it jour(s) de retard" },
            dueInDays = { "Dans $it jour(s)" },
            noCollections = "Aucune dette à relancer pour le moment",
            remindWhatsApp = "Rappel WhatsApp",
            recordPayment = "Enregistrer un paiement",
            settleFullCustomer = "Encaisser tout le solde",
            settleFullSupplier = "Payer tout le solde",
            fullSettlementNote = "Règlement total du solde",
            attachDocument = "Joindre une image ou un PDF",
            replaceAttachment = "Remplacer la pièce jointe",
            removeAttachment = "Supprimer la pièce jointe",
            attachmentAdded = "Document joint",
            openAttachment = "Ouvrir la pièce jointe",
            biometricLock = "Verrouillage biométrique",
            biometricLockDesc = "Demander l’empreinte à l’ouverture de DeynBook",
            biometricUnavailable = "L’authentification biométrique n’est pas disponible ou configurée sur cet appareil",
            unlock = "Déverrouiller",
            unlockTitle = "DeynBook est verrouillé",
            unlockSubtitle = "Utilisez votre empreinte pour accéder aux données de dettes",
            calendarTitle = "Système de date",
            gregorianCalendar = "Calendrier grégorien",
            ethiopianCalendar = "Calendrier éthiopien",
            reminderMessage = { name, amount, due -> "Bonjour $name, petit rappel amical : le solde dû est de $amount et l’échéance est le $due. Merci." }
        )
        AppLanguage.ENGLISH -> FeatureStrings(
            collectionCenter = "Collection Center",
            collectionSubtitle = "Track due and overdue debts in one place",
            overdue = "Overdue",
            dueToday = "Due today",
            dueSoon = "Due soon",
            upcoming = "Upcoming",
            dueDate = "Due date",
            noDueDate = "No due date",
            setDueDate = "Set due date",
            clearDueDate = "Clear due date",
            overdueDays = { "$it day(s) overdue" },
            dueInDays = { "Due in $it day(s)" },
            noCollections = "No debts need collection follow-up right now",
            remindWhatsApp = "WhatsApp reminder",
            recordPayment = "Record payment",
            settleFullCustomer = "Receive full balance",
            settleFullSupplier = "Pay full balance",
            fullSettlementNote = "Full balance settlement",
            attachDocument = "Attach image or PDF",
            replaceAttachment = "Replace attachment",
            removeAttachment = "Remove attachment",
            attachmentAdded = "Document attached",
            openAttachment = "Open attachment",
            biometricLock = "Biometric app lock",
            biometricLockDesc = "Require fingerprint when opening DeynBook",
            biometricUnavailable = "Biometric authentication is unavailable or not enrolled on this device",
            unlock = "Unlock app",
            unlockTitle = "DeynBook is locked",
            unlockSubtitle = "Use your fingerprint to access debt data",
            calendarTitle = "Date system",
            gregorianCalendar = "Gregorian calendar",
            ethiopianCalendar = "Ethiopian calendar",
            reminderMessage = { name, amount, due -> "Hi $name, this is a friendly reminder that the outstanding balance is $amount and the due date is $due. Thank you." }
        )
    }
}
